#!/usr/bin/env bash
set -euo pipefail

SITE_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
BLOG_SRC="$HOME/Documents/Writing/blog/"
POSTS_DST="$SITE_ROOT/_posts/"

# Calculate the proper kebab-case name with date prefix
get_proper_name() {
  local src="$1"
  local basename="${src##*/}"
  local name_only="${basename%.*}"
  local ext="${basename##*.}"

  # Extract date from frontmatter or use file mtime
  local date
  if [[ -f "$src" ]]; then
    date=$(sed -n '/^date: /p' "$src" | head -1 | sed 's/^date: *\([0-9\-]*\).*/\1/')
    if [[ -z "$date" ]]; then
      date=$(date -d "@$(stat -c %Y "$src")" +%Y-%m-%d)
    fi
  else
    return 0
  fi

  # Convert to kebab-case: lowercase, replace spaces/underscores with hyphens
  name_only=$(echo "$name_only" | tr '[:upper:]' '[:lower:]' | sed 's/[_[:space:]]/-/g' | sed 's/-\+/-/g' | sed 's/^-\|-$//g')

  # Remove existing date prefix if present
  name_only=$(echo "$name_only" | sed 's/^[0-9]\{4\}-[0-9]\{2\}-[0-9]\{2\}-//')

  echo "$date-$name_only.$ext"
}

# Rename file in-place if it doesn't have the correct format
rename_in_place() {
  local src="$1"
  local basename="${src##*/}"
  local proper_name=$(get_proper_name "$src")

  if [[ "$basename" != "$proper_name" ]]; then
    local dir="${src%/*}"
    local new_path="$dir/$proper_name"
    mv "$src" "$new_path"
    echo "$new_path"
  else
    echo "$src"
  fi
}

mkdir -p "$BLOG_SRC" "$POSTS_DST"

# Track which posts exist in source (by new name)
declare -A synced_posts

# Rename files in blog dir and sync to posts
for post in "$BLOG_SRC"/*.md; do
  [[ -e "$post" ]] || continue

  # Rename in-place if needed
  post=$(rename_in_place "$post")

  # Copy to posts dir
  new_name=$(basename "$post")
  cp "$post" "$POSTS_DST/$new_name"
  synced_posts["$new_name"]=1

  # Check for spanish: true flag and translate if present
  if grep -q "^spanish: true" "$POSTS_DST/$new_name" 2>/dev/null; then
    "$SITE_ROOT/translate-post.sh" "$POSTS_DST/$new_name" 2>&1 || true
    # Remove spanish: true flag from source and posts (translation handled)
    sed -i '/^spanish: true/d' "$post"
    sed -i '/^spanish: true/d' "$POSTS_DST/$new_name"
  fi
done

# Remove posts that no longer exist in source (but skip Spanish posts — they're generated)
for post in "$POSTS_DST"/*.md; do
  [[ -e "$post" ]] || continue
  basename="${post##*/}"
  # Skip Spanish posts (lang: es) — they're generated by translate-post.sh, not synced from blog/
  if grep -q "^lang: es" "$post" 2>/dev/null; then
    continue
  fi
  if [[ -z "${synced_posts[$basename]:-}" ]]; then
    rm "$post"
  fi
done

# Commit changes in Writing repo if it exists
WRITING_REPO="$(cd "$BLOG_SRC" 2>/dev/null && cd .. && pwd 2>/dev/null)" || WRITING_REPO=""
if [[ -n "$WRITING_REPO" && -d "$WRITING_REPO/.git" ]]; then
  (
    cd "$WRITING_REPO"
    git add -A
    if ! git diff --cached --quiet 2>/dev/null; then
      git commit -m "blog: rename posts to kebab-case with date" || true
    fi
  ) || true
fi

cd "$SITE_ROOT" || { echo "ERROR: cannot cd to $SITE_ROOT"; exit 1; }

# Stage changes
if ! git add -A 2>&1; then
  echo "ERROR: git add failed"
  exit 1
fi

# Check if there are changes
if git diff --cached --quiet 2>/dev/null; then
  echo "blog: no changes"
  exit 0
fi

# Commit
if ! git commit -m "blog: sync $(date +%Y-%m-%d\ %H:%M)" 2>&1; then
  echo "ERROR: git commit failed"
  exit 1
fi

# Push (warn but don't fail)
if ! git push 2>&1; then
  echo "⚠️  git push failed (auth, network, or remote issue) — commit is local"
  exit 0
fi
