#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

# Update modDatetime for modified blog markdown files

git diff --cached --name-status | grep -i '^M.*src/data/blog/.*\.md$' | while read _ file; do
  filecontent=$(cat "$file")
  frontmatter=$(echo "$filecontent" | awk -v RS='---' 'NR==2{print}')
  draft=$(echo "$frontmatter" | awk '/^draft: /{print $2}')
  if [ "$draft" = "false" ]; then
    echo "$file modDateTime updated"
    cat $file | sed "/---.*/,/---.*/s/^modDatetime:.*$/modDatetime: $(date -u "+%Y-%m-%dT%H:%M:%SZ")/" > tmp && mv tmp $file
    git add $file
  fi
  if [ "$draft" = "first" ]; then
    echo "First release of $file, draft set to false and modDateTime removed"
    cat $file | sed "/---.*/,/---.*/s/^modDatetime:.*$/modDatetime:/" | sed "/---.*/,/---.*/s/^draft:.*$/draft: false/" > tmp && mv tmp $file
    git add $file
  fi
done

# Add pubDatetime for new blog markdown files
git diff --cached --name-status | grep -i '^A.*src/data/blog/.*\.md$' | while read _ file; do
  cat $file | sed "/---.*/,/---.*/s/^pubDatetime:.*$/pubDatetime: $(date -u "+%Y-%m-%dT%H:%M:%SZ")/" > tmp && mv tmp $file
  git add $file
done
