name: CI

permissions:
  contents: read

on:
  pull_request:
    types:
      - opened
      - edited
      - synchronize
      - reopened
  workflow_call:

jobs:
  build:
    name: Build site
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: "☁️ Checkout repository"
        uses: actions/checkout@v4

      - name: "💎 Setup Ruby"
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: "🚀 Build the site"
        run: bundle exec jekyll build
